/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERACION_H_RPCGEN
#define _OPERACION_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_OP 20
#define MAX_STR 256

struct Operacion {
	char *username;
	char *op;
	char *datetime;
	char *filename;
};
typedef struct Operacion Operacion;

#define IMPRIMIR_OPERACION 500
#define IMPRIMIR_OPERACION_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define print_operacion 1
extern  enum clnt_stat print_operacion_1(struct Operacion , void *, CLIENT *);
extern  bool_t print_operacion_1_svc(struct Operacion , void *, struct svc_req *);
extern int imprimir_operacion_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print_operacion 1
extern  enum clnt_stat print_operacion_1();
extern  bool_t print_operacion_1_svc();
extern int imprimir_operacion_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operacion (XDR *, Operacion*);

#else /* K&R C */
extern bool_t xdr_Operacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERACION_H_RPCGEN */
