/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
*/

#include "operacion.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#define MAX_MSG 1024
#define MAX_STR 256
#define MAX_OP 20

bool_t print_operacion_1_svc(struct Operacion arg1, void *result,  struct svc_req *rqstp) {
	bool_t retval = true;

	char nombre[MAX_STR];
	char operacion[MAX_OP];
	char fichero[MAX_STR];
	char datetime[MAX_STR];

	// Obtener los argumentos
	strcpy(nombre, arg1.username);
	strcpy(operacion, arg1.op);
	strcpy(fichero, arg1.filename);
	strcpy(datetime, arg1.datetime);

	char op[280];

	if (strcmp(fichero, "") != 0) {
		snprintf(op, 280, "%s %s", operacion, fichero);
	} else {
		strcpy(op, operacion);
	}

	// Crear mensaje
	printf("%s\t%s  \t%s\n", nombre, op, datetime);

	return retval;
}

int imprimir_operacion_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result) {
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
