/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operacion.h"

bool_t
xdr_Operacion (XDR *xdrs, Operacion *objp)
{
	// register int32_t *buf;

	if (!xdr_string (xdrs, &objp->username, MAX_STR))
		return FALSE;
	if (!xdr_string (xdrs, &objp->op, MAX_OP))
		return FALSE;
	if (!xdr_string (xdrs, &objp->datetime, MAX_STR))
		return FALSE;
	if (!xdr_string (xdrs, &objp->filename, MAX_STR))
		return FALSE;

	return TRUE;
}
