/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "operacion.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_operacion_1(struct Operacion arg1, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, print_operacion,
		(xdrproc_t) xdr_Operacion, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
